[vars]
nix_chroot_bin = "nix-user-chroot ~/.nix ~/.nix-profile/bin"
nix_bin = '{{vars.nix_chroot_bin}}/nix --extra-experimental-features "nix-command flakes"'

[tasks.fmt]
description = "Run nixfmt via nix-user-chroot"
run = "{{vars.nix_chroot_bin}}/nix-shell -p nixfmt-tree --run \"treefmt ${@:-.}\""

[tasks."secret:renc"]
alias = "renc"
description = "Run vaultix renc"
run = "{{vars.nix_bin}} run $'.?submodules=1#vaultix.app.x86_64-linux.renc'"

[tasks."secret:edit"]
alias = "sedit"
description = "Run vaultix renc"
run = "{{vars.nix_bin}} run $'.?submodules=1#vaultix.app.x86_64-linux.edit'"

[tasks.commit-secrets]
dir = "secrets"
run = ["git add .", "git commit -m {{usage.message | quote}}"]
usage = '''arg <message> default="Update secrets"'''

[tasks.deploy-vm]
vars._.file = "secrets/mise_vars.txt"
description = "Deploy configuration to a machine using nixos-anywhere"
# TODO: 1. ssh-keygen a keypair to /tmp, 2. decrypt zfs passphrase via age, 3. Provide password via env.SSHPASS
interactive = true
run = [
	'cd secrets && mise run decrypt-secrets',
	'''{{vars.nix_bin}} run github:nix-community/nixos-anywhere -- --flake '.?submodules=1#{{vars.sandbox1_name}}' --extra-files /tmp/{{vars.sandbox1_name}}/keys --disk-encryption-keys /tmp/zfs-secret.key ~/zfs-pass.txt root@{{vars.sandbox1_ip}}''',
	'''sed -i '/^{{vars.sandbox1_ip}}/D' /home/kroot/.ssh/known_hosts''',
]

[tasks.rebuild-vm]
vars._.file = "secrets/mise_vars.txt"
description = "Invoke nixos-rebuild remotely to vm"
# TODO: 1. ssh-keygen a keypair to /tmp, 2. decrypt zfs passphrase via age, 3. Provide password via env.SSHPASS
interactive = true
run = '''{{vars.nix_bin}} run nixpkgs#nixos-rebuild -- switch --flake '.?submodules=1#{{vars.sandbox1_name}}' --target-host root@nixos-vm'''

[tasks.deploy-homelab]
vars._.file = "secrets/mise_vars.txt"
description = "Deploy configuration to a machine using nixos-anywhere"
# TODO: 1. ssh-keygen a keypair to /tmp, 2. decrypt zfs passphrase via age, 3. Provide password via env.SSHPASS
interactive = true
run = [
	'cd secrets && mise run decrypt-secrets',
	'''{{vars.nix_bin}} run github:nix-community/nixos-anywhere -- --flake '.?submodules=1#{{vars.homelab1_name}}' --extra-files /tmp/{{vars.homelab1_name}}/keys --disk-encryption-keys /tmp/zfs-secret.key ~/zfs-pass.txt root@{{vars.homelab1_name}}''',
	'''sed -i '/^{{vars.homelab1_ip}}/D' /home/kroot/.ssh/known_hosts''',
]

[tasks.rebuild-homelab]
vars._.file = "secrets/mise_vars.txt"
description = "Invoke nixos-rebuild remotely to homelab"
interactive = true
run = '''{{vars.nix_bin}} run nixpkgs#nixos-rebuild -- switch --flake '.?submodules=1#{{vars.homelab1_name}}' --target-host root@{{vars.homelab1_name}}'''

[tasks.check-homelab]
vars._.file = "secrets/mise_vars.txt"
description = "Dry-activate nixos-rebuild remotely for homelab"
interactive = true
run = '''{{vars.nix_bin}} run nixpkgs#nixos-rebuild -- dry-activate --flake '.?submodules=1#{{vars.homelab1_name}}' --target-host root@{{vars.homelab1_name}}'''

[tasks."flake:update"]
alias = "up"
run = "{{vars.nix_bin}} flake update"

[tasks."nix:bare"]
alias = "nix"
run = "{{vars.nix_bin}} "

[tasks.build-iso]
alias = "iso"
shell = "zsh -c"
run = [
	"rm -f result",
	'cd secrets && mise run decrypt-secrets && git add live-ssh-key',
	"{{vars.nix_bin}} build $'.?submodules=1#nixosConfigurations.nixos-live.config.system.build.isoImage'",
	'cd secrets && git restore --staged live-ssh-key',
	'ln -sf ${$(readlink ./result):s|/nix|~/.nix} ./result',
	'''sed -i '/^192./D' /home/kroot/.ssh/known_hosts''',
]
